Dataset = Amazon Product Reviews Dataset
Dataset Kaggle Link = https://www.kaggle.com/datasets/yasserh/amazon-product-reviews-dataset

# Part1

# Task1

In [14]:
import pandas as pd 

df = pd.read_csv('C:/Users/kumar/OneDrive/Desktop/TRY-2/Tasks-Submission/Assignment17/7817_1.csv')
df.shape
df.columns

Index(['id', 'asins', 'brand', 'categories', 'colors', 'dateAdded',
       'dateUpdated', 'dimension', 'ean', 'keys', 'manufacturer',
       'manufacturerNumber', 'name', 'prices', 'reviews.date',
       'reviews.doRecommend', 'reviews.numHelpful', 'reviews.rating',
       'reviews.sourceURLs', 'reviews.text', 'reviews.title',
       'reviews.userCity', 'reviews.userProvince', 'reviews.username', 'sizes',
       'upc', 'weight'],
      dtype='object')

In [16]:
!pip install nltk

Collecting nltk
  Using cached nltk-3.9.2-py3-none-any.whl.metadata (3.2 kB)
Requirement already satisfied: click in c:\conda\envs\venv\lib\site-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in c:\conda\envs\venv\lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in c:\conda\envs\venv\lib\site-packages (from nltk) (2026.1.15)
Requirement already satisfied: tqdm in c:\conda\envs\venv\lib\site-packages (from nltk) (4.67.2)
Requirement already satisfied: colorama in c:\users\kumar\appdata\roaming\python\python310\site-packages (from click->nltk) (0.4.6)
Using cached nltk-3.9.2-py3-none-any.whl (1.5 MB)
Installing collected packages: nltk
Successfully installed nltk-3.9.2

In [17]:
import pandas as pd
import re
import nltk
import string

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\kumar\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt.zip.
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\kumar\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\kumar\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [19]:
# Load dataset (example)
df = pd.read_csv('C:/Users/kumar/OneDrive/Desktop/TRY-2/Tasks-Submission/Assignment17/7817_1.csv')

# Select text column
text_col = "reviews.text"

# First 5 text samples
print(df[text_col].head())

# Length of each text
df["text_length"] = df[text_col].astype(str).apply(len)
print(df["text_length"].head())

0    I initially had trouble deciding between the p...
1    Allow me to preface this with a little history...
2    I am enjoying it so far. Great for reading. Ha...
3    I bought one of the first Paperwhites and have...
4    I have to say upfront - I don't like coroporat...
Name: reviews.text, dtype: object
0    1064
1    1424
2     182
3    1671
4    1916
Name: text_length, dtype: int64

# Task2

In [20]:
def basic_clean(text):
    text = str(text).lower()
    text = re.sub(r'\d+', '', text)                 # remove numbers
    text = text.translate(str.maketrans('', '', string.punctuation))
    text = re.sub(r'\s+', ' ', text).strip()        # remove extra spaces
    return text

df["clean_text_basic"] = df[text_col].apply(basic_clean)

# Compare original vs cleaned
df[[text_col, "clean_text_basic"]].head()

,reviews.text,clean_text_basic
0,I initially had trouble deciding between the p...,i initially had trouble deciding between the p...
1,Allow me to preface this with a little history...,allow me to preface this with a little history...
2,I am enjoying it so far. Great for reading. Ha...,i am enjoying it so far great for reading had ...
3,I bought one of the first Paperwhites and have...,i bought one of the first paperwhites and have...
4,I have to say upfront - I don't like coroporat...,i have to say upfront i dont like coroporate h...

# Part2

# Task3

In [21]:
def advanced_clean(text):
    text = str(text).lower()
    text = re.sub(r'http\S+|www\S+', '', text)       # URLs
    text = re.sub(r'\S+@\S+', '', text)              # emails
    text = re.sub(r'<.*?>', '', text)                # HTML tags
    text = re.sub(r'[^a-z\s]', '', text)             # special chars & emojis
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df["clean_text_advanced"] = df["clean_text_basic"].apply(advanced_clean)

# Task4

In [29]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\kumar\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping tokenizers\punkt_tab.zip.

True

In [30]:
stop_words = set(stopwords.words('english'))

def remove_stopwords(text):
    words = word_tokenize(text)
    return " ".join([w for w in words if w not in stop_words])

df["text_no_stopwords"] = df["clean_text_advanced"].apply(remove_stopwords)

# Task5

In [31]:
slang_dict = {
    "u": "you",
    "gr8": "great"
}

def normalize_text(text):
    # normalize repeated characters
    text = re.sub(r'(.)\1{2,}', r'\1\1', text)
    
    # replace slang
    words = text.split()
    words = [slang_dict.get(w, w) for w in words]
    return " ".join(words)

df["normalized_text"] = df["text_no_stopwords"].apply(normalize_text)

# Part3

# Task6

In [32]:
# Word Tokenization
df["word_tokens"] = df["normalized_text"].apply(word_tokenize)

# Sentence Tokenization (show 3 samples)
for i in range(3):
    print(sent_tokenize(df[text_col].iloc[i]))

["I initially had trouble deciding between the paperwhite and the voyage because reviews more or less said the same thing: the paperwhite is great, but if you have spending money, go for the voyage.Fortunately, I had friends who owned each, so I ended up buying the paperwhite on this basis: both models now have 300 ppi, so the 80 dollar jump turns out pricey the voyage's page press isn't always sensitive, and if you are fine with a specific setting, you don't need auto light adjustment).It's been a week and I am loving my paperwhite, no regrets!", 'The touch screen is receptive and easy to use, and I keep the light at a specific setting regardless of the time of day.', "(In any case, it's not hard to change the setting either, as you'll only be changing the light level at a certain time of day, not every now and then while reading).Also glad that I went for the international shipping option with Amazon.", 'Extra expense, but delivery was on time, with tracking, and I didnt need to worry about customs, which I may have if I used a third party shipping service.']
['Allow me to preface this with a little history.', 'I am (was) a casual reader who owned a Nook Simple Touch from 2011.', "I've read the Harry Potter series, Girl with the Dragon Tattoo series, 1984, Brave New World, and a few other key titles.", 'Fair to say my Nook did not get as much use as many others may have gotten from theirs.Fast forward to today.', "I have had a full week with my new Kindle Paperwhite and I have to admit, I'm in love.", 'Not just with the Kindle, but with reading all over again!', 'Now let me relate this review, love, and reading all back to the Kindle.', 'The investment of 139.00 is in the experience you will receive when you buy a Kindle.', 'You are not simply paying for a screen there is an entire experience included in buying from Amazon.I have been reading The Hunger Games trilogy and shall be moving onto the Divergent series soon after.', 'Here is the thing with the Nook that hindered me for the past 4 years: I was never inspired to pick it up, get it into my hands, and just dive in.', 'There was never that feeling of oh man, reading on this thing is so awesome.', 'However, with my Paperwhite, I now have that feeling!', 'That desire is back and I simply adore my Kindle.', 'If you are considering purchasing one, stop thinking about it simply go for it.', 'After a full week, 3 downloaded books, and a ton of reading, I still have half of my battery left as well.Make yourself happy.', 'Inspire the reader inside of you.']
['I am enjoying it so far.', 'Great for reading.', 'Had the original Fire since 2012.', 'The Fire used to make my eyes hurt if I read too long.', "Haven't experienced that with the Paperwhite yet."]

# Task7

In [33]:
stemmer = PorterStemmer()

def stem_words(tokens):
    return [stemmer.stem(word) for word in tokens]

df["stemmed_words"] = df["word_tokens"].apply(stem_words)

# Compare
df[["word_tokens", "stemmed_words"]].head()

,word_tokens,stemmed_words
0,"[initially, trouble, deciding, paperwhite, voy...","[initi, troubl, decid, paperwhit, voyag, revie..."
1,"[allow, preface, little, history, casual, read...","[allow, prefac, littl, histori, casual, reader..."
2,"[enjoying, far, great, reading, original, fire...","[enjoy, far, great, read, origin, fire, sinc, ..."
3,"[bought, one, first, paperwhites, pleased, con...","[bought, one, first, paperwhit, pleas, constan..."
4,"[say, upfront, dont, like, coroporate, hermeti...","[say, upfront, dont, like, coropor, hermet, cl..."

# Task8

In [34]:
lemmatizer = WordNetLemmatizer()

def lemmatize_words(tokens):
    return [lemmatizer.lemmatize(word) for word in tokens]

df["lemmatized_words"] = df["word_tokens"].apply(lemmatize_words)

# Compare stemming vs lemmatization
df[["stemmed_words", "lemmatized_words"]].head()

,stemmed_words,lemmatized_words
0,"[initi, troubl, decid, paperwhit, voyag, revie...","[initially, trouble, deciding, paperwhite, voy..."
1,"[allow, prefac, littl, histori, casual, reader...","[allow, preface, little, history, casual, read..."
2,"[enjoy, far, great, read, origin, fire, sinc, ...","[enjoying, far, great, reading, original, fire..."
3,"[bought, one, first, paperwhit, pleas, constan...","[bought, one, first, paperwhites, pleased, con..."
4,"[say, upfront, dont, like, coropor, hermet, cl...","[say, upfront, dont, like, coroporate, hermeti..."

# Task9

In [35]:
def nlp_preprocess(text):
    text = advanced_clean(text)
    tokens = word_tokenize(text)
    tokens = [w for w in tokens if w not in stop_words]
    tokens = [lemmatizer.lemmatize(w) for w in tokens]
    return tokens

df["final_clean_text"] = df[text_col].apply(nlp_preprocess)

# Task10

- Basic vs Advanced Cleaning

Basic cleaning removes casing, punctuation, numbers

Advanced cleaning removes URLs, emails, HTML, emojis → cleaner NLP input

- Lemmatization vs Stemming

Stemming cuts words aggressively (better → bet)

Lemmatization keeps meaningful words (better → good)

Lemmatization is preferred for NLP models

- Importance of Preprocessing

Reduces noise

Improves model accuracy

Ensures consistent vocabulary

Faster and better feature extraction