Dataset = Amazon Product Reviews Dataset
Dataset Kaggle Link = https://www.kaggle.com/datasets/yasserh/amazon-product-reviews-dataset

# Part1

In [2]:
import pandas as pd 

df = pd.read_csv('C:/Users/kumar/OneDrive/Desktop/TRY-2/Tasks-Submission/Assignment18/7817_1.csv')
df.shape
df.columns

Index(['id', 'asins', 'brand', 'categories', 'colors', 'dateAdded',
       'dateUpdated', 'dimension', 'ean', 'keys', 'manufacturer',
       'manufacturerNumber', 'name', 'prices', 'reviews.date',
       'reviews.doRecommend', 'reviews.numHelpful', 'reviews.rating',
       'reviews.sourceURLs', 'reviews.text', 'reviews.title',
       'reviews.userCity', 'reviews.userProvince', 'reviews.username', 'sizes',
       'upc', 'weight'],
      dtype='object')

In [3]:
import pandas as pd
import numpy as np

from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
text_col = "reviews.text"

# Drop missing values
texts = df[text_col].dropna()

# Task1

In [4]:
sentences = texts.iloc[:5].tolist()
vocab = sorted(set(" ".join(sentences).lower().split()))
print("Vocabulary:", vocab)
one_hot_vectors = []

for sentence in sentences:
    words = sentence.lower().split()
    vector = [1 if word in words else 0 for word in vocab]
    one_hot_vectors.append(vector)
one_hot_df = pd.DataFrame(one_hot_vectors, columns=vocab)
one_hot_df

Vocabulary: ['(buying', '(in', '(like', '(maybe', '(quotes', '(was)', '-', '139.00', '1984,', '2005', '2007', '2011.', '2012.', '3', '300', '4', '400.with', '80', 'a', 'about', 'accounts', 'accumulative', 'action', 'actions', 'actually', "adjustment).it's", 'admit,', 'adore', 'after', 'after.', 'again!', 'ah', 'alerts', 'all', 'allow', 'almost', 'also', 'always', 'am', 'amazon', 'amazon.', 'amazon.i', 'amazons', 'an', 'and', 'any', 'anything', 'app', 'appears', 'apple', 'are', 'as', 'aspects', 'at', 'attractions', 'auto', 'average,', 'avoided.', 'awesome.', 'back', 'basis:', 'battery', 'be', 'because', 'become', 'been', 'begin', 'behave', 'believe', 'best', 'between', 'black', 'blotches', 'book', 'bookbub,', 'books', 'books,', 'books.', 'both', 'bottom', 'bought', 'brave', 'but', 'but...i', 'buy', 'buying', 'by', 'can', "can't", 'cant', 'capabilities)', 'case,', 'casing', 'casual', 'certain', 'change', 'changing', 'chosen', 'closed', 'cold', 'coming', 'companion', 'complete', 'consensus', 'considering', 'constant', 'cool', 'coroporate,', "couldn't", 'course,', 'creeping', 'critique.', 'customer', 'customs,', 'daily', 'dark', 'day,', 'day.', 'days', 'dead', 'deals', 'deciding', 'definitely', 'delivers,', 'delivery', 'desire', 'devices', 'did', 'did.', 'didnt', 'directly,', 'disperses', 'dive', 'divergent', 'do', 'does)...', "doesn't", 'dollar', "don't", 'downloaded', 'dragon', 'drives', 'each,', 'easy', 'effect', 'either,', 'enabled', 'ended', 'enjoying', 'entire', 'even', 'ever', 'every', 'exactly', 'except', 'expected', 'expense,', 'experience', 'experienced', 'extra', 'eyes', 'fair', 'fairly', 'far,', 'far.', 'feeling', 'feeling!', 'few', 'figure', 'fine', 'fine,', 'fine.', 'fingers.for', 'fire', 'first', 'flakey', 'for', 'forward', 'found', 'friends', "friends'", 'from', 'full', 'fully', 'funcion', 'functionalities', 'future', 'games', 'general', 'genres.', 'get', 'girl', 'give', 'glacial.', 'glad', 'go', 'good', 'goodreads)', 'gotten', 'great', 'great,', 'guy.i', 'had', 'half', 'hand,', 'hands,', 'hang', 'happy', 'happy.', 'hard', 'harry', 'has', 'have', "haven't", 'having', 'here', 'hermetically', 'hindered', 'history.', 'hold', 'how', 'however', 'however,', 'hunger', 'hurt', 'i', "i'd", "i'm", "i've", 'if', 'im', 'in', 'in.', 'included', 'initially', 'inside', 'inspire', 'inspired', 'international', 'into', 'investment', 'iphone.', 'is', "isn't", 'it', "it's", 'it,', 'it.', 'its', 'itso', 'ive', 'jump', 'just', 'keep', 'key', 'kindle', 'kindle,', 'kindle.', 'kindle.of', 'knew', 'least', 'left', 'less', 'let', 'level', 'life.so', 'light', 'like', 'list', 'little', 'live', 'logistical', 'long.', 'lost', 'love,', 'love.', 'loving', 'mad.', 'made', 'make', 'malfunctioning.', 'man,', 'manner.', 'many', 'marvelous', 'may', 'me', 'member', 'mind,', 'mine.', 'models', 'money,', 'more', 'moving', 'much', 'my', 'naturally,', 'need', 'never', 'new', 'no', 'nook', 'not', 'noticed', 'now', 'number', 'of', 'oh', 'on', 'on.the', 'once', 'one', 'one,', 'one.read', 'ones', 'online', 'only', 'onto', 'option', 'or', 'original', 'other', 'others', 'out', 'out.the', 'over', 'own', 'own,', 'owned', 'packaging', 'page', 'page-turning', 'paperwhite', "paperwhite's", 'paperwhite,', 'paperwhites', 'party', 'past', 'paying', 'perfect,', 'pick', 'picture', 'picture)', 'plastic', 'pleased', 'positively', 'potter', 'ppi,', 'preface', 'press', 'pricey', 'problem', 'problems', 'pry', 'purchasing', 'put', 'read', 'read,', 'reader', 'reading', 'reading).also', 'reading,', 'reading.', 'really', 'reasons,', 'receive', 'receptive', 'recommend', 'regardless', 'regrets!', 'relate', 'remained', 'remains', 'review,', 'reviews', 'said', 'same', 'same,', 'say', 'screen', 'screen,', 'screen/light', 'second', 'see', 'seems', 'seen', 'sensitive,', 'serbia', 'serbia,', 'serbia.', 'series', 'series,', 'service.', 'setting', 'setting,', 'several', 'shadows', 'shall', 'sharing', 'shipping', 'ships', 'sideloaded', 'similar', 'simple', 'simply', 'since', 'sits', 'size', 'slow', 'slow,', 'so', 'some', 'somewhere,', 'soon', 'specific', 'spending', 'states', 'still', 'stop', 'store', 'stuff', 'sundry', 'suppose', 'tab', 'take', 'tattoo', 'technology', 'that', "that's", 'that,', 'the', 'their', 'theirs.fast', 'them', 'them,', 'them.', 'then', 'there', 'there!', 'theres', 'these', 'thing', 'thing:', 'think', 'thinking', 'third', 'this', 'thousands', 'three', 'through', 'thus', 'time', 'time,', 'time.', 'titles.', 'to', 'today.', 'ton', 'too', 'touch', 'touchscreen', 'tracking,', 'treat', 'trilogy', 'trouble', 'turns', 'two', 'two.', 'up', 'up,', 'up.', 'upfront', 'upgrades:', 'upward', 'usability', 'use', 'use,', 'used', 'user', 'using', 'very', 'voyage', "voyage's", 'voyage.fortunately,', 'waiting', 'want', 'was', 'week', 'week,', 'well', 'well.make', 'went', 'what', 'when', 'which', 'while', 'who', 'why', 'will', 'with', 'without', 'works', 'world,', 'worry', 'would', 'wouldnt', 'years', 'years,', 'years:', 'yet.', 'you', "you'll", 'you.', 'you.as', 'youd', 'yourself']

,(buying,(in,(like,(maybe,(quotes,(was),-,139.00,"1984,",2005,...,years,"years,",years:,yet.,you,you'll,you.,you.as,youd,yourself
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,1,0,0,0,0
1,0,0,0,0,0,1,0,1,1,0,...,0,0,1,0,1,0,1,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,1,1,0
4,1,0,1,1,1,0,1,0,0,1,...,0,1,0,0,1,0,0,0,0,0

# Task2

In [5]:
vectorizer_oh = CountVectorizer(binary=True)
X_oh = vectorizer_oh.fit_transform(sentences)
# Vocabulary
print(vectorizer_oh.vocabulary_)
# Encoded matrix
pd.DataFrame(X_oh.toarray(), columns=vectorizer_oh.get_feature_names_out())

{'initially': 205, 'had': 180, 'trouble': 402, 'deciding': 104, 'between': 58, 'the': 374, 'paperwhite': 292, 'and': 32, 'voyage': 417, 'because': 51, 'reviews': 328, 'more': 258, 'or': 282, 'less': 227, 'said': 329, 'same': 330, 'thing': 382, 'is': 213, 'great': 178, 'but': 68, 'if': 201, 'you': 440, 'have': 189, 'spending': 361, 'money': 257, 'go': 174, 'for': 155, 'fortunately': 156, 'friends': 159, 'who': 428, 'owned': 289, 'each': 124, 'so': 356, 'ended': 129, 'up': 406, 'buying': 70, 'on': 274, 'this': 386, 'basis': 48, 'both': 64, 'models': 256, 'now': 270, '300': 7, 'ppi': 304, '80': 9, 'dollar': 119, 'jump': 219, 'turns': 404, 'out': 286, 'pricey': 307, 'page': 291, 'press': 306, 'isn': 214, 'always': 27, 'sensitive': 337, 'are': 38, 'fine': 150, 'with': 431, 'specific': 360, 'setting': 341, 'don': 120, 'need': 263, 'auto': 43, 'light': 231, 'adjustment': 16, 'it': 215, 'been': 53, 'week': 421, 'am': 28, 'loving': 241, 'my': 261, 'no': 266, 'regrets': 323, 'touch': 397, 'screen': 332, 'receptive': 320, 'easy': 125, 'to': 393, 'use': 411, 'keep': 221, 'at': 41, 'regardless': 322, 'of': 272, 'time': 391, 'day': 100, 'in': 203, 'any': 33, 'case': 75, 'not': 268, 'hard': 186, 'change': 79, 'either': 127, 'as': 39, 'll': 236, 'only': 279, 'be': 50, 'changing': 80, 'level': 229, 'certain': 78, 'every': 134, 'then': 378, 'while': 427, 'reading': 316, 'also': 26, 'glad': 173, 'that': 373, 'went': 423, 'international': 209, 'shipping': 346, 'option': 281, 'amazon': 29, 'extra': 141, 'expense': 138, 'delivery': 107, 'was': 420, 'tracking': 399, 'didnt': 111, 'worry': 435, 'about': 10, 'customs': 97, 'which': 426, 'may': 250, 'used': 412, 'third': 385, 'party': 294, 'service': 340, 'allow': 24, 'me': 252, 'preface': 305, 'little': 234, 'history': 195, 'casual': 77, 'reader': 315, 'nook': 267, 'simple': 350, 'from': 160, '2011': 5, 've': 415, 'read': 314, 'harry': 187, 'potter': 303, 'series': 339, 'girl': 170, 'dragon': 122, 'tattoo': 371, '1984': 2, 'brave': 67, 'new': 265, 'world': 434, 'few': 148, 'other': 284, 'key': 222, 'titles': 392, 'fair': 143, 'say': 331, 'did': 110, 'get': 169, 'much': 260, 'many': 248, 'others': 285, 'gotten': 177, 'theirs': 376, 'fast': 146, 'forward': 157, 'today': 394, 'full': 161, 'kindle': 223, 'admit': 17, 'love': 240, 'just': 220, 'all': 23, 'over': 287, 'again': 20, 'let': 228, 'relate': 324, 'review': 327, 'back': 47, 'investment': 211, '139': 1, '00': 0, 'experience': 139, 'will': 430, 'receive': 319, 'when': 425, 'buy': 69, 'simply': 351, 'paying': 296, 'there': 379, 'an': 31, 'entire': 131, 'included': 204, 'hunger': 199, 'games': 166, 'trilogy': 401, 'shall': 344, 'moving': 259, 'onto': 280, 'divergent': 115, 'soon': 359, 'after': 19, 'here': 192, 'hindered': 194, 'past': 295, 'years': 438, 'never': 264, 'inspired': 208, 'pick': 298, 'into': 210, 'hands': 183, 'dive': 114, 'feeling': 147, 'oh': 273, 'man': 246, 'awesome': 46, 'however': 198, 'desire': 108, 'adore': 18, 'considering': 88, 'purchasing': 311, 'one': 276, 'stop': 364, 'thinking': 384, 'downloaded': 121, 'books': 63, 'ton': 395, 'still': 363, 'half': 181, 'battery': 49, 'left': 226, 'well': 422, 'make': 244, 'yourself': 442, 'happy': 185, 'inspire': 207, 'inside': 206, 'enjoying': 130, 'far': 145, 'original': 283, 'fire': 152, 'since': 352, '2012': 6, 'eyes': 142, 'hurt': 200, 'too': 396, 'long': 238, 'haven': 190, 'experienced': 140, 'yet': 439, 'bought': 66, 'first': 153, 'paperwhites': 293, 'very': 416, 'pleased': 301, 'its': 216, 'constant': 89, 'companion': 85, 'suppose': 368, 'ive': 218, 'average': 44, 'book': 61, 'three': 388, 'days': 101, 'wouldnt': 437, 'give': 171, 'youd': 441, 'pry': 310, 'cold': 83, 'dead': 102, 'fingers': 151, 'sundry': 367, 'logistical': 237, 'reasons': 318, 'made': 243, 'good': 175, 'amazons': 30, 'app': 35, 'iphone': 212, 'naturally': 262, 'cool': 90, 'usability': 410, 'delivers': 106, 'works': 433, 'has': 188, 'own': 288, 'attractions': 42, 'course': 93, 'aspects': 40, 'would': 436, 'like': 232, 'critique': 95, 'ah': 21, 'knew': 224, 'coming': 84, 'somewhere': 358, 'member': 253, 'bookbub': 62, 'daily': 98, 'list': 233, 'alerts': 22, 'deals': 103, 'chosen': 81, 'genres': 168, 'take': 370, 'them': 377, 'found': 158, 'even': 132, 'best': 57, 'cant': 73, 'some': 357, 'seems': 335, 'two': 405, 'theres': 380, 'stuff': 366, 'accumulative': 12, 'effect': 126, 'number': 271, 'actually': 15, 'creeping': 94, 'ever': 133, 'upward': 409, '400': 8, 'mind': 254, 'noticed': 269, 'turning': 403, 'remained': 325, 'exactly': 135, 'action': 13, 'become': 52, 'positively': 302, 'glacial': 172, 'slow': 355, 'think': 383, 'malfunctioning': 245, 'general': 167, 'consensus': 87, 'appears': 36, 'expected': 137, 'once': 275, 'begin': 54, 'behave': 55, 'flakey': 154, 'manner': 247, 'drives': 123, 'mad': 242, 'states': 362, 'can': 72, 'hold': 196, 'thousands': 387, 'believe': 56, 'figure': 149, 'second': 333, 'im': 202, 'waiting': 418, 'actions': 14, 'complete': 86, 'upfront': 407, 'coroporate': 91, 'hermetically': 193, 'closed': 82, 'anything': 34, 'by': 71, 'apple': 37, 'having': 191, 'devices': 109, 'put': 312, 'want': 419, 'fairly': 144, 'user': 413, 'several': 342, 'couldn': 92, 'functionalities': 164, 'live': 235, 'serbia': 338, 'lost': 239, 'fully': 162, 'using': 414, 'their': 375, 'online': 278, 'capabilities': 74, 'except': 136, 'ships': 347, 'customer': 96, '2005': 3, 'accounts': 11, '2007': 4, 'through': 389, 'definitely': 105, 'technology': 372, 'why': 429, 'itso': 217, 'what': 424, 'similar': 349, 'problem': 308, 'mine': 255, 'disperses': 113, 'black': 59, 'blotches': 60, 'maybe': 251, 'see': 334, 'picture': 299, 'bottom': 65, 'shadows': 343, 'plastic': 300, 'casing': 76, 'thus': 390, 'really': 317, 'avoided': 45, 'without': 432, 'marvelous': 249, 'touchscreen': 398, 'store': 365, 'these': 381, 'guy': 179, 'hang': 184, 'how': 197, 'sideloaded': 348, 'least': 225, 'almost': 25, 'do': 116, 'future': 165, 'upgrades': 408, 'treat': 400, 'ones': 277, 'directly': 112, 'sharing': 345, 'funcion': 163, 'quotes': 313, 'goodreads': 176, 'enabled': 128, 'size': 354, 'perfect': 297, 'sits': 353, 'hand': 182, 'doesn': 118, 'dark': 99, 'tab': 369, 'does': 117, 'packaging': 290, 'problems': 309, 'remains': 326, 'seen': 336, 'life': 230, 'recommend': 321}

,00,139,1984,2005,2007,2011,2012,300,400,80,...,works,world,worry,would,wouldnt,years,yet,you,youd,yourself
0,0,0,0,0,0,0,0,1,0,1,...,0,0,1,0,0,0,0,1,0,0
1,1,1,1,0,0,1,0,0,0,0,...,0,1,0,0,0,1,0,1,0,1
2,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,0,0,0,1,0,...,1,1,0,1,1,1,0,1,1,0
4,0,0,0,1,1,0,0,1,0,0,...,1,0,0,0,0,1,0,1,0,0

# Part2

# Task3

In [6]:
bow_vectorizer = CountVectorizer()
X_bow = bow_vectorizer.fit_transform(texts)
# Vocabulary size
print("Vocabulary size:", len(bow_vectorizer.vocabulary_))
# Sample feature vectors
pd.DataFrame(X_bow[:5].toarray(),
             columns=bow_vectorizer.get_feature_names_out()).head()

Vocabulary size: 6469

,00,000,000s,04,07,08,0x0,10,100,1000,...,zarathustra,zen,zero,zink,zip,zippy,zombies,zoom,zooming,zumi
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Task4

In [7]:
word_freq = np.array(X_bow.sum(axis=0)).flatten()
freq_df = pd.DataFrame({
    "word": bow_vectorizer.get_feature_names_out(),
    "frequency": word_freq
}).sort_values(by="frequency", ascending=False)
# Top 10
freq_df.head(10)
# Least frequent
freq_df.tail(10)

         word  frequency
30       1292          1
18        110          1
6434       ye          1
6448     youd          1
15      10min          1
13       1080          1
2        000s          1
6467  zooming          1
6466     zoom          1
6465  zombies          1

Explanation (for report)

Bag of Words captures how many times each word appears in the corpus, ignoring grammar and word order, but preserving frequency information.

# Part3

# Task5

In [8]:
# Unigrams
uni = CountVectorizer(ngram_range=(1,1))
X_uni = uni.fit_transform(texts)

# Bigrams
bi = CountVectorizer(ngram_range=(2,2))
X_bi = bi.fit_transform(texts)

# Trigrams
tri = CountVectorizer(ngram_range=(3,3))
X_tri = tri.fit_transform(texts)
print("Unigram vocab size:", len(uni.vocabulary_))
print("Bigram vocab size:", len(bi.vocabulary_))
print("Trigram vocab size:", len(tri.vocabulary_))
# Sample vectors
X_bi[:3].toarray()

Unigram vocab size: 6469
Bigram vocab size: 51225
Trigram vocab size: 88399

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(3, 51225))

# Task6

In [9]:
combined = CountVectorizer(ngram_range=(1,2))
X_combined = combined.fit_transform(texts)

print("Combined vocab size:", len(combined.vocabulary_))

Combined vocab size: 57694

# Part4

# Task7

In [10]:
tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(texts)
# Vocabulary
len(tfidf.vocabulary_)
# TF-IDF matrix shape
X_tfidf.shape

(1597, 6469)

# Task8

In [11]:
tfidf_df = pd.DataFrame(
    X_tfidf.toarray(),
    columns=tfidf.get_feature_names_out()
)

In [12]:
tfidf_df.mean().sort_values(ascending=False).head(10)

the     0.157836
to      0.100471
and     0.085501
it      0.082189
is      0.067385
for     0.052971
you     0.050949
this    0.050494
of      0.050429
my      0.043577
dtype: float64

In [13]:
tfidf_df.mean().sort_values().head(10)

219        0.000013
2093       0.000013
1292       0.000013
000s       0.000013
track      0.000013
289        0.000013
simples    0.000013
lasta      0.000013
caught     0.000013
formata    0.000013
dtype: float64

# Part5

# Task9

In [14]:
vec1 = CountVectorizer(max_features=500)
vec2 = CountVectorizer(min_df=5)
vec3 = CountVectorizer(max_df=0.7)

print(len(vec1.fit(texts).vocabulary_))
print(len(vec2.fit(texts).vocabulary_))
print(len(vec3.fit(texts).vocabulary_))

500
2510
6465

# Task10

1 One-Hot vs BoW

One-Hot → presence/absence

BoW → frequency based

2 Why N-grams increase dimensionality

Each word combination becomes a new feature

3 When to prefer TF-IDF

When common words dominate and importance matters

4 Limitations of count-based methods

No semantics

No word order

High dimensionality