dataset_name = Student performance dataset
kaggle_link = https://www.kaggle.com/datasets/devansodariya/student-performance-data

# Part1

In [1]:
import pandas as pd

df = pd.read_csv('C:/Users/kumar/OneDrive/Desktop/TRY-2/Tasks-Submission/Assignment14/student_data.csv')

# Print shape
print("Shape:", df.shape)

# Column names
print("\nColumns:\n", df.columns)

# First 5 rows
df.head()

Shape: (395, 33)

Columns:
 Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

# Task1

In [ ]:
# Average grade of first two exams
df['avg_G1_G2'] = (df['G1'] + df['G2']) / 2

# Total alcohol consumption
df['total_alcohol'] = df['Dalc'] + df['Walc']

# Age group from age
df['age_group'] = pd.cut(
    df['age'],
    bins=[14, 16, 18, 22],
    labels=['15-16', '17-18', '19+']
)

# Performance category from final grade
df['performance'] = pd.cut(
    df['G3'],
    bins=[-1, 9, 14, 20],
    labels=['Poor', 'Average', 'Good']
)

df.head()

# Task2

# Part2

# Task3

In [2]:
cat_cols = df.select_dtypes(include='object').columns
print(cat_cols)
df_encoded = pd.get_dummies(df, columns=cat_cols, drop_first=True)
df_encoded.head()

Index(['school', 'sex', 'address', 'famsize', 'Pstatus', 'Mjob', 'Fjob',
       'reason', 'guardian', 'schoolsup', 'famsup', 'paid', 'activities',
       'nursery', 'higher', 'internet', 'romantic'],
      dtype='object')

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,guardian_mother,guardian_other,schoolsup_yes,famsup_yes,paid_yes,activities_yes,nursery_yes,higher_yes,internet_yes,romantic_yes
0,18,4,4,2,2,0,4,3,4,1,...,True,False,True,False,False,False,True,True,False,False
1,17,1,1,1,2,0,5,3,3,1,...,False,False,False,True,False,False,False,True,True,False
2,15,1,1,1,2,3,4,3,2,2,...,True,False,True,False,True,False,True,True,True,False
3,15,4,2,1,3,0,3,2,2,1,...,True,False,False,True,True,True,True,True,True,True
4,16,3,3,1,2,0,4,3,2,1,...,False,False,False,True,True,False,True,True,False,False

# Task4

In [17]:
cat_cols = df.select_dtypes(include='object').columns

In [18]:
df_encoded = pd.get_dummies(df, columns=cat_cols, drop_first=True)

In [19]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['school_encoded'] = le.fit_transform(df['school'])

# Part3

# Task5

In [3]:
from sklearn.preprocessing import StandardScaler

num_cols = df.select_dtypes(include='number').columns

scaler = StandardScaler()
df_standardized = df.copy()

df_standardized[num_cols] = scaler.fit_transform(df[num_cols])

df_standardized[num_cols].describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,3.950000e+02,3.950000e+02,3.950000e+02,3.950000e+02,3.950000e+02,3.950000e+02,3.950000e+02,3.950000e+02,3.950000e+02,3.950000e+02,3.950000e+02,3.950000e+02,3.950000e+02,3.950000e+02,3.950000e+02,3.950000e+02
mean,1.223213e-15,5.396527e-17,-1.439074e-16,6.295948e-17,-2.113640e-16,-1.349132e-17,-1.394103e-16,1.079305e-16,-1.214219e-16,1.349132e-16,-1.798842e-16,7.195369e-17,-5.396527e-17,8.994212e-17,-4.946817e-17,-9.443922e-17
std,1.001268e+00,1.001268e+00,1.001268e+00,1.001268e+00,1.001268e+00,1.001268e+00,1.001268e+00,1.001268e+00,1.001268e+00,1.001268e+00,1.001268e+00,1.001268e+00,1.001268e+00,1.001268e+00,1.001268e+00,1.001268e+00
min,-1.330954e+00,-2.514630e+00,-2.320084e+00,-6.432495e-01,-1.235351e+00,-4.499436e-01,-3.287804e+00,-2.240828e+00,-1.896683e+00,-5.406987e-01,-1.003789e+00,-1.839649e+00,-7.142362e-01,-2.385787e+00,-2.851920e+00,-2.276226e+00
25%,-5.462869e-01,-6.853872e-01,-4.798568e-01,-6.432495e-01,-1.235351e+00,-4.499436e-01,6.219406e-02,-2.360102e-01,-9.972953e-01,-5.406987e-01,-1.003789e+00,-3.992895e-01,-7.142362e-01,-8.774869e-01,-4.562264e-01,-5.278366e-01
50%,2.383798e-01,2.292342e-01,-4.798568e-01,-6.432495e-01,-4.228585e-02,-4.499436e-01,6.219406e-02,-2.360102e-01,-9.790798e-02,-5.406987e-01,-2.263446e-01,3.208902e-01,-2.137958e-01,2.749306e-02,7.615005e-02,1.278095e-01
75%,1.023046e+00,1.143856e+00,4.402569e-01,7.922508e-01,-4.228585e-02,-4.499436e-01,1.178860e+00,7.663987e-01,8.014793e-01,5.833854e-01,5.511000e-01,1.041070e+00,2.866447e-01,6.308130e-01,6.085265e-01,7.834555e-01
max,4.161713e+00,1.143856e+00,1.360371e+00,3.663251e+00,2.343844e+00,3.589323e+00,1.178860e+00,1.768808e+00,1.700867e+00,3.955638e+00,2.105989e+00,1.041070e+00,8.669022e+00,2.440773e+00,2.205656e+00,2.094748e+00

# Task6

In [4]:
from sklearn.preprocessing import MinMaxScaler

minmax = MinMaxScaler()
df_normalized = df.copy()

df_normalized[num_cols] = minmax.fit_transform(df[num_cols])

df_normalized[num_cols].describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,395.000000,395.000000,395.00000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000,395.000000
mean,0.242315,0.687342,0.63038,0.149367,0.345148,0.111392,0.736076,0.558861,0.527215,0.120253,0.322785,0.638608,0.076118,0.494304,0.563891,0.520759
std,0.182292,0.273684,0.27205,0.232502,0.279747,0.247884,0.224165,0.249716,0.278320,0.222685,0.321974,0.347576,0.106708,0.207450,0.197974,0.229072
min,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.142857,0.500000,0.50000,0.000000,0.000000,0.000000,0.750000,0.500000,0.250000,0.000000,0.000000,0.500000,0.000000,0.312500,0.473684,0.400000
50%,0.285714,0.750000,0.50000,0.000000,0.333333,0.000000,0.750000,0.500000,0.500000,0.000000,0.250000,0.750000,0.053333,0.500000,0.578947,0.550000
75%,0.428571,1.000000,0.75000,0.333333,0.333333,0.000000,1.000000,0.750000,0.750000,0.250000,0.500000,1.000000,0.106667,0.625000,0.684211,0.700000
max,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

# Part4

# Task7

In [5]:
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

num_features = df.select_dtypes(include='number').columns
cat_features = df.select_dtypes(include='object').columns
numeric_pipeline = Pipeline([
    ('scaler', StandardScaler())
])

categorical_pipeline = Pipeline([
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])
preprocessor = ColumnTransformer([
    ('num', numeric_pipeline, num_features),
    ('cat', categorical_pipeline, cat_features)
])

# Task8

In [10]:
X = df.drop('G3', axis=1)
y = df['G3']

In [11]:
num_features = X.select_dtypes(include='number').columns
cat_features = X.select_dtypes(include='object').columns

In [12]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [13]:
numeric_pipeline = Pipeline([
    ('scaler', StandardScaler())
])

categorical_pipeline = Pipeline([
    ('encoder', OneHotEncoder(handle_unknown='ignore'))
])

preprocessor = ColumnTransformer([
    ('num', numeric_pipeline, num_features),
    ('cat', categorical_pipeline, cat_features)
])

In [14]:
model_pipeline = Pipeline([
    ('preprocessing', preprocessor),
    ('model', LinearRegression())
])

In [15]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model_pipeline.fit(X_train, y_train)

y_pred = model_pipeline.predict(X_test)

# Task9

1️⃣ Why pipelines are important?

They ensure consistent preprocessing, prevent data leakage, and simplify workflows.

2️⃣ What problems do pipelines solve?

Manual preprocessing errors

Train–test data leakage

Reproducibility issues

3️⃣ Manual vs Pipeline preprocessing
Manual	Pipeline
Error-prone	Safer
Repetitive	Reusable
Hard to deploy	Production-ready